language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.0
    - extra-google-m2repository
    - extra-android-m2repository
    - android-23
    - sys-img-x86-android-18
jdk:
  # - openjdk8 # not yet available
  - oraclejdk8
